import BlogBanner from '@/components/blog/BlogBanner'
import AllBlog from '@/components/blog/allBlogs/AllBlog'
import ContactUs from '@/components/shared/contactUs/ContactUs'
import Layout from '@/layout/Layout'
import Head from 'next/head'

const Blog = () => {
  return (
    <Layout>
      <Head>
        <title>Techvers | Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BlogBanner/>
      <AllBlog/>
      <ContactUs/>
    </Layout>
  )
}

export default Blog