import ContactBanner from '@/components/contact/ContactBanner'
import Address from '@/components/contact/address/Address'
import ContactUs from '@/components/shared/contactUs/ContactUs'
import Layout from '@/layout/Layout'
import Head from 'next/head'

const Contact = () => {
  return (
    <Layout>
      <Head>
        <title>Techvers | Contact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContactBanner/>
      <Address/>
      <ContactUs/>
    </Layout>
  )
}

export default Contact