import Company from "@/components/company/Company";
import Banner from "@/components/home/Banner";
import Blog from "@/components/home/Blog";
import About from "@/components/home/about/About";
import Projects from "@/components/home/projects/Projects";
import Service from "@/components/home/service/Service";
import ContactUs from "@/components/shared/contactUs/ContactUs";
import WorkingProcess from "@/components/shared/workingProcess/WorkingProcess";
import Layout from "@/layout/Layout";
import Head from "next/head";

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Techvers | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner/>
      <About/>
      <Service/>
      <WorkingProcess/>
      <Projects/>
      <Company/>
      <ContactUs/>
      <Blog/>
    </Layout>
  )
}
