import ServiceBanner from '@/components/service/ServiceBanner'
import AllService from '@/components/service/allService/AllService'
import WorkingProcess from '@/components/shared/workingProcess/WorkingProcess'
import Layout from '@/layout/Layout'
import Head from 'next/head'

const Service = () => {
  return (
    <Layout>
      <Head>
        <title>Techvers | Service</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ServiceBanner/>
      <AllService/>
      <WorkingProcess/>
    </Layout>
  )
}

export default Service