import ContactUs from '@/components/shared/contactUs/ContactUs'
import TestimonialBanner from '@/components/testimonial/TestimonialBanner'
import Testimonials from '@/components/testimonial/Testimonials'
import Layout from '@/layout/Layout'
import Head from 'next/head'

const Testimonial = () => {
  return (
    <Layout>
      <Head>
        <title>Techvers | Testimonial</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TestimonialBanner/>
      <Testimonials/>
      <ContactUs/>
    </Layout>
  )
}

export default Testimonial